spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:local_test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop